### ISSUE TITLE
网络不可用

### ISSUE THREAD

**Issue by mavenjan** [chaychan/TouTiao#11]
提示错误
[ (NewsListPresenter.java:48)#onError ] java.lang.IllegalStateException:##  Expected an int but was BOOLEAN at line 1 column 1010 path $.has_m3u8_video
实体类对象数据类型错误

**Comment by chaychan** [comment]
@mavenjan 因为头条的接口返回值改了，视频现在也获取不到数据，现在正在修复。

**Comment by mavenjan** [comment]
嗯，头条的接口算是开放的么？@chaychan

**Comment by chaychan** [comment]
@mavenjan 不是开放的，是通过抓包分析，研究请求链接，请求参数的意义还有返回的json数据

**Comment by mavenjan** [comment]
那如果拿来用，涉及版权问题么？

**Comment by chaychan** [comment]
@mavenjan 因为获取新闻的接口，并非得到今日头条的许可，只是用抓包获取， 如果用作商业用途，会侵犯今日头条的权利，我这里只是用作技术交流。

**Comment by zhangsuper** [comment]
网络不可用，什么时候可以修复
