### ISSUE TITLE
接口调整，程序崩溃

### ISSUE THREAD

**Issue by mavenjan** [chaychan/TouTiao#14]
NewsAdapter: data----------->[]

 java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.chaychan.news.model.entity.ImageEntity.url' on a null object reference                                                                 at com.chaychan.news.ui.adapter.NewsAdapter$1.getItemType(NewsAdapter.java:89)
at com.chaychan.news.ui.adapter.NewsAdapter$1.getItemType(NewsAdapter.java:78)

**Comment by chaychan** [comment]
@mavenjan 多谢反馈，待修复

**Comment by mavenjan** [comment]
一直在参考学习^_^.
你是用fiddler抓包的么？

**Comment by chaychan** [comment]
是的

**Comment by mavenjan** [comment]
更新到最新版的fiddler后gg了，得重新破解了。方便qq好友或者微信好友么？以便交流学习^_^

**Comment by ZhangLanqiu** [comment]
一进主界面就崩。。。。  今日头条的接口很调皮老是改来改去的

**Comment by ZhangLanqiu** [comment]
奇怪了，今日头条app我N久不更新！ 数据显示也没有问题，估计他们的接口处理方式很特殊，不知道怎么做到的

**Comment by chaychan** [comment]
@ZhangLanqiu 他们集成热更新的，不用升级APP，靠打补丁。

**Comment by ZhangLanqiu** [comment]
忘了这茬，不过博主是否考虑也集成 hotfix 呀， 目前在照着你的项目学习呢（无耻的伸手党 (｀・ω・´)）

**Comment by chaychan** [comment]
@ZhangLanqiu 这个建议好，我也正想尝试下

**Comment by mavenjan** [comment]
之前有做过andfix热更新。最近看阿里技术总结了Android热修复技术原理。有兴趣可以共同学习下。最近还没学习了
