### ISSUE TITLE
视频播放问题

### ISSUE THREAD

**Issue by xianxianbuxian** [chaychan/TouTiao#21]
Response:{"retCode":300,"retDesc":"页面停留时间过长，请强制刷新当前页. :)","data":null,"succ":false}
 地址访问就405 大神什么时候修复啊

**Comment by chaychan** [comment]
之前比较忙，现在已经修复

**Comment by xianxianbuxian** [comment]
嗯嗯 已经看到了 大神辛苦了

**Comment by chaychan** [comment]
@xianxianbuxian 之前用的是第三方的解析视频的接口，现在他们收费，我只好采取WebView读取新闻网页，注入js获取到video标签的src，从而获取到视频地址
