### ISSUE TITLE
视频放不了，刷新视频列表，闪退，然后启动就闪退，一直闪退？

### ISSUE THREAD

**Issue by meicuihui** [chaychan/TouTiao#23]

**Comment by chaychan** [comment]
清除数据后进入还会吗

**Comment by dapengko1** [comment]
确实播放不了，获取的播放地址应该需要解析一遍，我看了下是跳转到ixigua.com了(西瓜视频的服务器地址吧)

**Comment by chaychan** [comment]
@dapengko1 已经修改视频地址解析的逻辑了，你可以更新下代码看看

**Comment by dapengko1** [comment]
就是用的最新代码，还是不能播放

**Comment by amsterly** [comment]
不能播放 今天下的！！！！

**Comment by chaychan** [comment]
刚发现解析视频的方法又用不了了，现在在寻找新的方法

**Comment by dapengko1** [comment]
我已经找到解决办法了，在VideoPathDecoder类中添加代码：
![image](https://user-images.githubusercontent.com/13550110/35497775-8a6e50bc-0506-11e8-8b5c-b478b28374ec.png)
现在视频里有4秒的广告，只有延迟等广告放完后再去加载JS。

**Comment by chaychan** [comment]
@dapengko1 其实我们的这种方案是没办法中的办法，用户体验不好，但是在没有提供接口的情况下只好这样子了，之前破解别人的接口，现在搞不了了，人家现在收费，每次0.01

**Comment by meicuihui** [comment]
我的天，还要收费呀
