### ISSUE TITLE
右滑关闭Activity（SlideCloseLib）不适配8.0系统全面屏手机，进入相关Activity会闪退

### ISSUE THREAD

**Issue by leemacTest** [chaychan/TouTiao#25]
右滑关闭Activity（SlideCloseLib）不适配8.0系统全面屏手机（华为手机），进入相关Activity会闪退
具体原因可以查看：https://www.jianshu.com/p/d0d907754603
大佬可否做一下适配

**Comment by chaychan** [comment]
@leemacTest  那个侧滑的方案并不是特别好，建议使用这个[https://github.com/anzewei/ParallaxBackLayout](https://github.com/anzewei/ParallaxBackLayout)
