### ISSUE TITLE
com.chaychan.library这个package的导入方式

### ISSUE THREAD

**Issue by WoXinfeiyang** [chaychan/TouTiao#28]
请教一下，com.chaychan.library这个package的源码在什么地方？为什么跟进去都是.class文件？查看了一下，既不是通过gradle引用远程库的方式导入也不是通过.jar的方式导入
![toutiao](https://user-images.githubusercontent.com/13744327/39301052-755e0f46-4980-11e8-8508-9dbe584e5122.png)

**Comment by chaychan** [comment]
那个是通过gradle导入的

**Comment by WoXinfeiyang** [comment]
我Ctrl+Shift+F全局搜索关键字“com.chaychan.library”没有找到啊
![gradle](https://user-images.githubusercontent.com/13744327/39344241-e1a2d43c-4a13-11e8-9e43-070f6ba7fd1d.png)
