### ISSUE TITLE
请教个关于侧滑关闭界面的问题

### ISSUE THREAD

**Issue by VanConsday** [chaychan/TouTiao#30]
侧滑关闭界面时，style中添加   android:windowIsTranslucent = true 这个属性，就会导致关闭后出现1s的白屏，demo 中并没有这个问题，我也没有找到解决的方法，还请指点一下

**Comment by chaychan** [comment]
@86userused 那个侧滑的方案并不是特别好，建议使用这个[https://github.com/anzewei/ParallaxBackLayout](https://github.com/anzewei/ParallaxBackLayout)

**Comment by davidgerka** [comment]
可以参考这个腾讯开源的UI库：https://github.com/Tencent/QMUI_Android，有用到侧滑返回的
