### ISSUE TITLE
现在有其他问题，装好之后，提示网络不给力，没有新闻和视频等列表

### ISSUE THREAD

**Issue by BlueTailCat** [chaychan/TouTiao#33]
现在有其他问题，装好之后，提示网络不给力，没有新闻和视频等列表

**Comment by chaychan** [comment]
@enric-lee 这边测试了没问题，网络不给力是因为加载不到数据，你检查下网络试试

**Comment by BlueTailCat** [comment]
网络没有问题，UC等app使用正常，我是api 28，android 9，荣耀V10手机。抓包如下：
03-20 14:43:51.306 32292-32292/com.chaychan.news D/ActivityThread: Attach thread to application
03-20 14:43:51.618 32292-32292/com.chaychan.news V/ActivityThread: Skipping new config:{1.0 460mcc2mnc [zh_CN_#Hans] ldltr sw360dp w360dp h696dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1080, 2160) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.11}, config:{1.0 460mcc2mnc [zh_CN_#Hans] ldltr sw360dp w360dp h696dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1080, 2160) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.11} for app:com.chaychan.news
03-20 14:43:51.651 32292-32292/com.chaychan.news V/ActivityThread: callActivityOnCreate
03-20 14:43:51.716 32292-32292/com.chaychan.news D/ActivityThread: add activity client record, r= ActivityRecord{947d398 token=android.os.BinderProxy@84cc78b {com.chaychan.news/com.chaychan.news.ui.activity.SplashActivity}} token= android.os.BinderProxy@84cc78b
03-20 14:43:53.756 32292-32292/com.chaychan.news V/ActivityThread: Skipping new config:{1.0 460mcc2mnc [zh_CN_#Hans] ldltr sw360dp w360dp h696dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1080, 2160) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.11}, config:{1.0 460mcc2mnc [zh_CN_#Hans] ldltr sw360dp w360dp h696dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 0, 0) mAppBounds=Rect(0, 0 - 1080, 2160) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.11} for app:com.chaychan.news
03-20 14:43:53.765 32292-32292/com.chaychan.news V/ActivityThread: callActivityOnCreate
03-20 14:43:53.840 32292-32292/com.chaychan.news D/ActivityThread: add activity client record, r= ActivityRecord{2b801a4 token=android.os.BinderProxy@65709e5 {com.chaychan.news/com.chaychan.news.ui.activity.MainActivity}} token= android.os.BinderProxy@65709e5
03-20 14:43:55.112 32292-32292/com.chaychan.news D/ActivityThread: Remove activity client record, r= ActivityRecord{947d398 token=android.os.BinderProxy@84cc78b {com.chaychan.news/com.chaychan.news.ui.activity.SplashActivity}} token= android.os.BinderProxy@84cc78b
03-20 14:44:46.292 32292-32292/com.chaychan.news V/ActivityThread: Handle window ActivityRecord{2b801a4 token=android.os.BinderProxy@65709e5 {com.chaychan.news/com.chaychan.news.ui.activity.MainActivity}} visibility: false
03-20 14:45:54.663 32292-32292/com.chaychan.news V/ActivityThread: Handle window ActivityRecord{2b801a4 token=android.os.BinderProxy@65709e5 {com.chaychan.news/com.chaychan.news.ui.activity.MainActivity}} visibility: false
03-20 15:08:54.681 32292-32292/com.chaychan.news D/JZVD: releaseAllVideos
03-20 15:08:54.682 32292-32292/com.chaychan.news D/ZrHung.AppEyeUiProbe: stop checker.
03-20 15:08:54.808 32292-32311/com.chaychan.news D/ZrHung.AppEyeUiProbe: Current Activity:false
    not watching, wait.
03-20 15:08:55.150 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,1,0 interval=3931
03-20 15:08:55.185 32292-32315/com.chaychan.news W/libEGL: EGLNativeWindowType 0x72332f5010 disconnect failed
03-20 15:08:55.211 32292-32292/com.chaychan.news D/ViewRootImpl[MainActivity]: surface should not be released
03-20 15:08:58.601 32292-32292/com.chaychan.news I/Choreographer: Skipped 89 frames!  The application may be doing too much work on its main thread.
03-20 15:09:45.748 32292-32292/com.chaychan.news I/Choreographer: Skipped 2134 frames!  The application may be doing too much work on its main thread.
03-20 15:09:45.759 32292-32299/com.chaychan.news W/m.chaychan.new: Receiving file descriptor from ADB failed (socket 46): Success
03-20 15:09:45.759 32292-32299/com.chaychan.news E/m.chaychan.new: Something went wrong getting fds from adb. Retry!: Success
03-20 15:10:28.929 32292-32292/com.chaychan.news D/ZrHung.AppEyeUiProbe: notify runnable to start.
03-20 15:10:28.929 32292-32311/com.chaychan.news D/ZrHung.AppEyeUiProbe: restart watching
03-20 15:10:28.961 32292-32315/com.chaychan.news D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
03-20 15:10:28.985 32292-32292/com.chaychan.news I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-20 15:10:28.987 32292-32292/com.chaychan.news W/InputMethodManager: startInputReason = 1
03-20 15:10:31.529 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,1,0 interval=466
03-20 15:10:31.794 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,2,0 interval=732
03-20 15:10:31.951 32292-32292/com.chaychan.news E/NewsListPresenter.java: [ (NewsListPresenter.java:48)#onError ] CLEARTEXT communication to is.snssdk.com not permitted by network security policy
03-20 15:10:32.047 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,3,0 interval=984
03-20 15:10:32.301 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,4,0 interval=1239
03-20 15:10:34.471 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,5,0 interval=3408
03-20 15:10:34.725 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,6,0 interval=3662
03-20 15:10:35.122 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,2,1,1,0 interval=96
03-20 15:10:35.134 32292-32292/com.chaychan.news V/AudioManager: playSoundEffect   effectType: 0
03-20 15:10:35.135 32292-32292/com.chaychan.news V/AudioManager: querySoundEffectsEnabled...
03-20 15:10:35.166 32292-32292/com.chaychan.news D/JZVD: releaseAllVideos
03-20 15:10:35.176 32292-32292/com.chaychan.news I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
03-20 15:10:35.219 32292-32292/com.chaychan.news E/NewsListPresenter.java: [ (NewsListPresenter.java:48)#onError ] CLEARTEXT communication to is.snssdk.com not permitted by network security policy
03-20 15:10:35.383 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,2,1,2,0 interval=358
03-20 15:10:35.638 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,2,1,3,0 interval=612
03-20 15:10:36.955 32292-32292/com.chaychan.news E/NewsListPresenter.java: [ (NewsListPresenter.java:48)#onError ] CLEARTEXT communication to is.snssdk.com not permitted by network security policy
03-20 15:10:36.956 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,4,0 interval=1931
03-20 15:10:37.217 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,5,0 interval=2191
03-20 15:10:37.471 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,6,0 interval=2445
03-20 15:10:37.743 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,7,0 interval=2717
03-20 15:10:37.996 32292-32292/com.chaychan.news D/HwAppInnerBoostImpl: asyncReportData com.chaychan.news,1,1,8,0 interval=2970

**Comment by BlueTailCat** [comment]
我把target_version改为了28，百度了下可能是这个原因，建议，我改为27试下。

**Comment by BlueTailCat** [comment]
切换成27就好了，28的安全限制有点高

**Comment by chaychan** [comment]
@enric-lee 好的
