### ISSUE TITLE
发现个BUG ，比如当前选项在第二个，第三个页面从来没加载过的情况下，标签管理删除了第二个，APP就崩溃了...

### ISSUE THREAD

**Issue by Feng-Cheng** [chaychan/TouTiao#40]
NullPointerException    发现个BUG ，比如当前选项在第二个，第三个页面从来没加载过的情况下，标签管理删除了第二个，APP就崩溃了...

**Comment by chaychan** [comment]
@Feng-Cheng 这边试了一下 复现不出 麻烦贴上报错的日志

**Comment by Feng-Cheng** [comment]
我这面项目是能跑，但日志不打印，   这么说吧 ！  你先把手机上安装的app删了，  然后重新安装一个，进去之后右滑一下到视频页，然后点击频道管理，把视频删除了，程序就崩溃了！   只要删除的当前频道后面一个频道没有初次加载过，程序都会崩溃的

**Comment by Feng-Cheng** [comment]
> @Feng-Cheng 这边试了一下 复现不出 麻烦贴上报错的日志

我这面项目是能跑，但日志不打印， 这么说吧 ！ 你先把手机上安装的app删了， 然后重新安装一个，进去之后右滑一下到视频页，然后点击频道管理，把视频删除了，程序就崩溃了！ 只要删除的当前频道后面一个频道没有初次加载过，程序都会崩溃的

**Comment by zhuzhutai** [comment]
这个动态的tab简直崩溃到怀疑人生... 切换编辑频道没做好
