### ISSUE TITLE
请问我上拉刷新需要改成请求网络数据具体怎么操作呢。

### ISSUE THREAD

**Issue by moscowneversleep** [chaychan/TouTiao#44]
![image](https://user-images.githubusercontent.com/26077379/78633834-26a5f900-78d5-11ea-9b52-a93abf7c7e9a.png)
修改zh这个方法 尤其他更好的方式嘛

**Comment by chaychan** [comment]
你只要在这个上拉刷新触发的回调中进行请求网络操作就行，我app里只是加载数据库里面的历史新闻

**Comment by moscowneversleep** [comment]
谢谢
