### ISSUE TITLE
請教一下

### ISSUE THREAD

**Issue by tenSunFree** [chaychan/TouTiao#7]
![01](https://user-images.githubusercontent.com/23090085/28904743-ada12a22-783f-11e7-879d-9210a6a241d1.jpg)
![02](https://user-images.githubusercontent.com/23090085/28904755-bb22c106-783f-11e7-93bb-37e9e857b1bf.jpg)
關於上圖的SharedPreferences 裡面的資料, 是在哪個階段放進去的?

**Comment by chaychan** [comment]
@tenSunFree 在HomeFragment的initChannelData()方法中，这里保存选中的频道是因为首页有个+号，用户可以更换选择显示的频道，只不过目前还没有实现那个功能。

**Comment by tenSunFree** [comment]
可是HomeFragment的initChannelData()方法, 是在我檢視SharedPreferences 裡面的資料之後
所以下圖 SharedPreferences 裡面的資料, 應該跟HomeFragment的initChannelData()方法 無關吧?
![03](https://user-images.githubusercontent.com/23090085/28906668-aed0bb04-784b-11e7-94ec-d96c91fcad44.jpg)

**Comment by chaychan** [comment]
@tenSunFree initChannelData()方法中，if判断是否有保存选中的频道的json或未选中频道的json，如果没有会将array_news.xml定义的数组添加到集合中，最后调用 selectedChannelJson = mGson.toJson(mSelectedChannels);//将集合转换成json字符串，再调用 PreUtils.putString(Constant.SELECTED_CHANNEL_JSON, selectedChannelJson);//保存到sp，你说的保存到SharedPreferences就是在这里保存的，PreUtils就是关于SharePrefrence的工具类。

**Comment by tenSunFree** [comment]
@chaychan 原來如此, 謝謝喔

**Comment by chaychan** [comment]
@tenSunFree 不用客气

**Comment by tenSunFree** [comment]
再請教一下, 如果把HomeFragment裡面的initChannelData 刪減成這樣
![2017-08-03_214612](https://user-images.githubusercontent.com/23090085/28924958-05701866-7896-11e7-80bd-fd8de3c49585.jpg)
省略了將mSelectedChannels 保存到SharedPreferences的動作, 似乎也是可以正常運作
那麼關於 保存到SharedPreferences的動作, 有它的必要性嗎?

**Comment by chaychan** [comment]
@tenSunFree 这样也是可以的，只不过每次它都需要通过读取string-array然后添加到集合，但是如果保存到SharePrefrence后，它可以直接读取SP中保存的json数组字符串，然后将他用Gson转换成对应的集合，效率上相对比较高。

**Comment by tenSunFree** [comment]
@chaychan 
如果我想觸發下圖 第二個Log, 我應該怎麼滑動? 
不管我怎麼滑動, 它都只會觸發第一個Log
![2017-08-04_003419](https://user-images.githubusercontent.com/23090085/28932820-69d1ffd8-78ad-11e7-85e8-617c5aa112be.jpg)
![2017-08-04_003951](https://user-images.githubusercontent.com/23090085/28932887-a072af06-78ad-11e7-8e9e-0ea7753b15b1.jpg)

**Comment by chaychan** [comment]
@tenSunFree 你好，之所以没有走到else，是因为SP中没有保存不要的频道，因为首页那个选择频道的功能尚未实现，所以此时未选频道是没有值的，你可以不考虑未选频道这个集合，就是说if判断中不考虑unSelectedChannel为空的情况，可以去掉，else中只是将SP中选中频道的json字符串转换成集合，未选中频道即不需要处理，你可以直接注释掉。

**Comment by tenSunFree** [comment]
@chaychan 懂了, 謝謝解惑

**Comment by chaychan** [comment]
@tenSunFree 不客气

**Comment by tenSunFree** [comment]
關於MainActivity裡面的 ViewPager
![01](https://user-images.githubusercontent.com/23090085/28954342-43163b2a-7911-11e7-8537-32e9f9540cbf.jpg)
它被設定成 不可左右滑動切換
![02](https://user-images.githubusercontent.com/23090085/28954351-5c46b084-7911-11e7-9112-d32722ef5ad0.jpg)
設定成不可左右滑動切換的動機 是什麼?

**Comment by chaychan** [comment]
@tenSunFree 因为MainActivity中的ViewPager是用于放置首页、视频、微头条、我的四个Fragment，其中首页和视频的Fragment布局都是TabLayout+ViewPager，今日头条的需求就是底部页签不需要滑动来切换，只是点击页签切换，而首页和视频中的ViewPager可以滑动切换，故MainActivity的ViewPager将其设置成不可滑动。

**Comment by tenSunFree** [comment]
@chaychan 了解, 謝謝喔
